// Generated by util.py
var node_imgs = {
    "soviet": {
        "Infantry": {
            "Combat Engineer": "images/nodes/soviet/Infantry/Combat Engineer.png",
            "Conscript": "images/nodes/soviet/Infantry/Conscript.png",
            "Flak Trooper": "images/nodes/soviet/Infantry/Flak Trooper.png",
            "Tesla Trooper": "images/nodes/soviet/Infantry/Tesla Trooper.png",
            "War Bear": "images/nodes/soviet/Infantry/War Bear.png",
        },
        "Production": {
            "Airfield": "images/nodes/soviet/Production/Airfield.png",
            "Barracks": "images/nodes/soviet/Production/Barracks.png",
            "Battle Bunker": "images/nodes/soviet/Production/Battle Bunker.png",
            "Construcion Yard": "images/nodes/soviet/Production/Construcion Yard.png",
            "Crusher Crane": "images/nodes/soviet/Production/Crusher Crane.png",
            "Ore Refinery": "images/nodes/soviet/Production/Ore Refinery.png",
            "Reactor": "images/nodes/soviet/Production/Reactor.png",
            "Super Reactor": "images/nodes/soviet/Production/Super Reactor.png",
            "War Factory": "images/nodes/soviet/Production/War Factory.png",
        },
    },
}
