import os

INDENT = "    "
NODES = os.path.join("images", "nodes")
JSFILE = "info.js"

def gen_path_dict_string(dirpath, depth=0):
    var_str = '{\n'
    for a in os.listdir(dirpath):
        a_path = os.path.join(dirpath, a)
        if os.path.isdir(a_path):
            var_str += '{}"{}": {},\n'.format(INDENT*(depth+1), a, gen_path_dict_string(a_path, depth+1))
        elif os.path.splitext(a)[1] in [".png"]:
            var_str += '{}"{}": "{}",\n'.format(INDENT*(depth+1), os.path.splitext(a)[0], a_path.replace("\\","/"))
    
    var_str += INDENT*depth + '}'
    
    return var_str

def main():
    node_str = gen_path_dict_string(NODES)
    content = "// Generated by util.py\n"
    content += "var node_imgs = {}\n".format(node_str)
    with open(JSFILE, 'w') as f:
        f.write(content)


if __name__ == '__main__':
    main()
    